name: Deploy Countdown Calendar
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.x
    - name: Publish .NET Core Project
      run: dotnet publish CountdownCalendar.csproj -c Release -o release --nologo
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.5
