name: Deploy Countdown Calendar
on:
  push:
    branches: [ main ]
jobs:  
  deploy-to-github-pages:
    permissions:
      contents: 'read'
      id-token: 'write'
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.x
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
    - name: Publish .NET Core Project
      run: dotnet publish CountdownCalendar.csproj -c:Release -p:GHPages=true -o:release --nologo
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main
        FOLDER: release/wwwroot
